### ISSUE TITLE
'stopped' event is mis-spelled

### ISSUE THREAD

**Issue by jbreadner** [alexfernandez/inits#1]
In 1.6.2, the following code does not work:

```
inits.on('stopped', () => {
  console.log('In "stopped" event');
});
```

But, this does:
```
inits.on('stoped', () => {
  console.log('In "stopped" event');
});
```

Documentation states that the event should be 'stopped'. 

edit: Thank you for the great utility, I've used this everywhere since discovering it!

**Comment by alexfernandez** [comment]
Should be solved in 1.6.3, just published; please reopen if necessary.
